<!-- BEGIN KEY -->
public class javax.security.sasl.AuthenticationException extends javax.security.sasl.SaslException
<!-- END KEY -->
<!-- BEGIN DATA -->
此异常由 SASL 机制实现抛出，指示由于和验证有关的原因（如无效的标识、口令 或密钥），SASL 交换已失败。
 <p>
注意，不出现 AuthenticationException 并不意味着失败不是由验证错误所导致的。如果 SASL 机制实现无法确定失败的类型，或者不想泄漏失败的类型（例如由于安全的原因），那么它可以抛出更通用的 SaslException 代替 AuthenticationException。

@since 1.5

@author Rosanna Lee
@author Rob Weltman

<!-- END DATA -->
<!-- BEGIN KEY -->
public javax.security.sasl.AuthenticationException()
<!-- END KEY -->
<!-- BEGIN DATA -->
构造一个新的 <tt>AuthenticationException</tt> 实例。根异常和详细消息为 null。

<!-- END DATA -->
<!-- BEGIN KEY -->
public javax.security.sasl.AuthenticationException(String detail)
<!-- END KEY -->
<!-- BEGIN DATA -->
构造带详细消息的新 <tt>AuthenticationException</tt> 实例。根异常为 null。
@param detail 包含异常细节的字符串，可能为 null。

@see java.lang.Throwable#getMessage

<!-- END DATA -->
<!-- BEGIN KEY -->
public javax.security.sasl.AuthenticationException(String detail, Throwable ex)
<!-- END KEY -->
<!-- BEGIN DATA -->
构造带详细消息和根异常的新 <tt>AuthenticationException</tt> 实例。

@param detail 包含异常细节的字符串，可能为 null。
@param ex 导致此异常的根异常，可能为 null。

@see java.lang.Throwable#getMessage
@see #getCause

<!-- END DATA -->
