<!-- BEGIN KEY -->
public class javax.transaction.xa.XAException extends java.lang.Exception
<!-- END KEY -->
<!-- BEGIN DATA -->
资源管理器 (RM) 抛出 XAException，以通知事务管理器涉及的事务遇到错误。


<!-- END DATA -->
<!-- BEGIN KEY -->
public int javax.transaction.xa.XAException.errorCode
<!-- END KEY -->
<!-- BEGIN DATA -->
用其创建 SystemException 的错误代码。

@serial 该异常的错误代码

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XA_RBBASE
<!-- END KEY -->
<!-- BEGIN DATA -->
回滚代码包含的下边界。

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XA_RBROLLBACK
<!-- END KEY -->
<!-- BEGIN DATA -->
指示未指定的原因导致该回滚。

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XA_RBCOMMFAIL
<!-- END KEY -->
<!-- BEGIN DATA -->
指示通讯失败导致该回滚。

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XA_RBDEADLOCK
<!-- END KEY -->
<!-- BEGIN DATA -->
检测死锁。

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XA_RBINTEGRITY
<!-- END KEY -->
<!-- BEGIN DATA -->
检测违反资源完整性的条件。

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XA_RBOTHER
<!-- END KEY -->
<!-- BEGIN DATA -->
由于一个不在此列表上的原因，资源管理器回滚事务分支。

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XA_RBPROTO
<!-- END KEY -->
<!-- BEGIN DATA -->
在资源管理器中发生协议错误。

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XA_RBTIMEOUT
<!-- END KEY -->
<!-- BEGIN DATA -->
事务分支占用时间太长。

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XA_RBTRANSIENT
<!-- END KEY -->
<!-- BEGIN DATA -->
可以重试事务分支。

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XA_RBEND
<!-- END KEY -->
<!-- BEGIN DATA -->
回滚错误代码包含的上边界。

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XA_NOMIGRATE
<!-- END KEY -->
<!-- BEGIN DATA -->
必须在发生挂起的地方发生恢复。

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XA_HEURHAZ
<!-- END KEY -->
<!-- BEGIN DATA -->
以启发式方式完成事务分支。

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XA_HEURCOM
<!-- END KEY -->
<!-- BEGIN DATA -->
以启发式方式提交事务分支。

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XA_HEURRB
<!-- END KEY -->
<!-- BEGIN DATA -->
以启发式方式回滚事务分支。

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XA_HEURMIX
<!-- END KEY -->
<!-- BEGIN DATA -->
以启发式方式提交并回滚事务分支。

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XA_RETRY
<!-- END KEY -->
<!-- BEGIN DATA -->
返回的例程无效，可以重新发布。

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XA_RDONLY
<!-- END KEY -->
<!-- BEGIN DATA -->
事务分支是只读的，并且已提交。

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XAER_ASYNC
<!-- END KEY -->
<!-- BEGIN DATA -->
已存在明显的异步操作。

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XAER_RMERR
<!-- END KEY -->
<!-- BEGIN DATA -->
在事务分支中发生资源管理器错误。

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XAER_NOTA
<!-- END KEY -->
<!-- BEGIN DATA -->
XID 无效。

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XAER_INVAL
<!-- END KEY -->
<!-- BEGIN DATA -->
提供了无效的参数。

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XAER_PROTO
<!-- END KEY -->
<!-- BEGIN DATA -->
在不合适的上下文中调用例程。

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XAER_RMFAIL
<!-- END KEY -->
<!-- BEGIN DATA -->
资源管理器不可用。

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XAER_DUPID
<!-- END KEY -->
<!-- BEGIN DATA -->
XID 已存在。

<!-- END DATA -->
<!-- BEGIN KEY -->
public static final int javax.transaction.xa.XAException.XAER_OUTSIDE
<!-- END KEY -->
<!-- BEGIN DATA -->
资源管理器进行全局事务之外的工作。

<!-- END DATA -->
<!-- BEGIN KEY -->
public javax.transaction.xa.XAException()
<!-- END KEY -->
<!-- BEGIN DATA -->
创建一个 XAException。

<!-- END DATA -->
<!-- BEGIN KEY -->
public javax.transaction.xa.XAException(String s)
<!-- END KEY -->
<!-- BEGIN DATA -->
创建一个具有给定字符串的 XAException。

@param s 包含异常消息的 <code>String</code> 对象。

<!-- END DATA -->
<!-- BEGIN KEY -->
public javax.transaction.xa.XAException(int errcode)
<!-- END KEY -->
<!-- BEGIN DATA -->
创建一个具有给定错误代码的 XAException。

@param errcode 标识异常的错误代码。

<!-- END DATA -->
